### ISSUE TITLE
Backend – Query Saving

### ISSUE THREAD

**Issue by StrangeRanger** [StrangeRanger/FAFB-PowerShell-Tool#72]
## Brief Overview

There must exist a button such that when pressed, a built query is saved for later use.

## User Stories / Use Cases 

As a user, I want to save PowerShell queries, so that I can use them again in the future.

## Acceptance Criteria

- A button to save the query.
- A section on the GUI where each query is saved and can be selected.
- A physical file that the queries are saved to.
  - The file should be a serialized `.dat` file.
    - There needs to be an agreed-upon format for this `.dat` file.

**Comment by J0seph0** [comment]
Like I said it is saving the query name but now needs to pull the parameters and design the json

**Comment by J0seph0** [comment]
Worked on this a little bit, need to now save the new parameters options

**Comment by J0seph0** [comment]
It saves to a file that is editable nicely with no issues
