### ISSUE TITLE
Backend – Load Saved Queries

### ISSUE THREAD

**Issue by StrangeRanger** [StrangeRanger/FAFB-PowerShell-Tool#75]
## Brief Overview

There must exist some functionality, where when a saved query is selected, it loads all of the commands, title, information, etc.

## User Stories / Use Cases 

As a user, I want to load saved queries, so I can execute them again.

## Acceptance Criteria

*List of criteria to meet for the requirement to be considered complete.*

**Comment by J0seph0** [comment]
Worked on this and can add buttons but now just need to add the buttons from the deserialized list

**Comment by J0seph0** [comment]
This is working correctly now
