### ISSUE TITLE
Duplicate parameters + values when saving a query

### ISSUE THREAD

**Issue by StrangeRanger** [StrangeRanger/FAFB-PowerShell-Tool#99]
**Describe the bug**
Sometimes, when saving a query, the application saves double the number of parameters + values than what was specified in the GUI.

**To Reproduce**
1. Start the application in a new session with no saved queries, and the data file containing saved queries doesn't exist.
2. Go to the "Query Builder" tab, and create and save a new query with the command, parameters, and its value filled out (i.e. `Get-ADUser -Filter *`.
3. The saved query should now be in the left sidebar.
4. Open the `CustomQueries.dat` file within the executable's directory.
5. You should now see something similar to the following:
	```dat
		{
			"$id": "1",
			"$values": [
			  {
			    "$id": "2",
			    "commandName": "Get-ADUser",
			    "commandParameters": [
			      "-Filter"
			    ],
			    "commandParametersValues": [
			      "*"
			    ],
			    "queryName": "",
			    "queryDescription": ""
			  }
			]
		}
	```
6. Now exit the file and return the application's "Query Builder" tab if you aren't already there.
7. Save the query once more; now, you should see a new saved query in the left sidebar.
8. Once again, open the `CustomQueries.dat` file.
9. You should now see something like the following:
	```dat
		{
		  "$id": "1",
		  "$values": [
		    {
		      "$id": "2",
		      "commandName": "Get-ADUser",
		      "commandParameters": [
		        "-Filter"
		      ],
		      "commandParametersValues": [
		        "*"
		      ],
		      "queryName": "",
		      "queryDescription": ""
		    },
		    {
		      "$id": "3",
		      "commandName": "Get-ADUser",
		      "commandParameters": [
		        "-Filter",
		        "-Filter"
		      ],
		      "commandParametersValues": [
		        "*",
		        "*"
		      ],
		      "queryName": "",
		      "queryDescription": ""
		    }
		  ]
		}
	```
10. Notice how the newest query has duplicate command parameters and values.

**Expected behavior**
I expect that it doesn't duplicate the number of present parameters. I expect it stores the exact number and parameter present in the GUI.

**Comment by J0seph0** [comment]
was able to go in and update the saving functionality to use the updateselectedcommand method to make sure the parameters are not duplicating
